// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBayEb5zMNGsoFB8elAHlnIrOfRooZpwGs',
    appId: '1:255668780311:web:ceccf4d390b8ec27450b52',
    messagingSenderId: '255668780311',
    projectId: 'musicdb-1c5c8',
    authDomain: 'musicdb-1c5c8.firebaseapp.com',
    storageBucket: 'musicdb-1c5c8.firebasestorage.app',
    measurementId: 'G-RVR5YWBTQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOyofvKMMZGjDHg4ETNzKwW3HiGpJs9fs',
    appId: '1:255668780311:android:75fb0705f5e4ef11450b52',
    messagingSenderId: '255668780311',
    projectId: 'musicdb-1c5c8',
    storageBucket: 'musicdb-1c5c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA9J4unO82nyO6N09KMYgtWUOtP_UJpMY',
    appId: '1:255668780311:ios:ecbaacd4118f1676450b52',
    messagingSenderId: '255668780311',
    projectId: 'musicdb-1c5c8',
    storageBucket: 'musicdb-1c5c8.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA9J4unO82nyO6N09KMYgtWUOtP_UJpMY',
    appId: '1:255668780311:ios:ecbaacd4118f1676450b52',
    messagingSenderId: '255668780311',
    projectId: 'musicdb-1c5c8',
    storageBucket: 'musicdb-1c5c8.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBayEb5zMNGsoFB8elAHlnIrOfRooZpwGs',
    appId: '1:255668780311:web:cabfc35a5f01f571450b52',
    messagingSenderId: '255668780311',
    projectId: 'musicdb-1c5c8',
    authDomain: 'musicdb-1c5c8.firebaseapp.com',
    storageBucket: 'musicdb-1c5c8.firebasestorage.app',
    measurementId: 'G-CBDD39P4JY',
  );
}
